### ISSUE TITLE
User can still be retrieved via token after logout in Laravel Sanctum (Authentication)

### ISSUE THREAD

**Issue by darbaoui** [laravel/sanctum#551]
### Laravel Version

11.20.0

### PHP Version

8.2.11

### Description

I am using Sanctum (Laravel Auth), which utilizes **requestGuard**. The authentication behavior seems correct, I can retrieve user data using their token without any issues. However, when I logout the user and remove their token, I can still fetch the user data using the removed token. Why is this happening?

```php
$request->user()->currentAccessToken()->delete();
```
To ensure this doesn’t happen, I added the following line after deleting the token:

```php
app($auth)->guard($current_guard)->forgetUser();
```

**For Tests**
If I use two requests with two different tokens, I notice that both requests return the user related to the first request's token. To handle this, should I add the following line between the two requests.

```php
app($auth)->guard($current_guard)->forgetUser();
```

### Steps To Reproduce

The steps to reproduce the issue

1. Create a user user `$user = User::factory()->create();`
2. Generate a token use `$token = $user->createToken('token-name', ['*'])->plainTextToken;`
3. Use the $token in the Authorization => 'Bearer '.$token
4. Now you can get the user data
5. remove the token using `$request->user()->currentAccessToken()->delete()`; because `Auth::logout();` only for **SessionGuard** i guess.
6. Use the step 3 again, and you can get the user data ?

**Comment by shaedrich** [comment]
Can you please rename your issue to something along the lines of "Use can still be retrieved via token after logout in Laravel Sanctum" so it has a descriptive title?

**Comment by bijaydas** [comment]
Is your code open-source? Cause I tried on my system with a new Laravel project and Sanctum package. It's working as expected.

**Comment by darbaoui** [comment]
Good this is a repos with the issue.
https://github.com/darbaoui/TestLaravelAuthentication

Tests fail as expected
https://github.com/darbaoui/TestLaravelAuthentication/actions/runs/12124543818/job/33802495384

Tests code
https://github.com/darbaoui/TestLaravelAuthentication/blob/main/tests/Feature/AuthenticationTest.php

**Comment by macropay-solutions** [comment]
@darbaoui
Is this happening also when you remove manually from db (personal_access_tokens table) the access token?

**Comment by darbaoui** [comment]
@macropay-solutions 
All the scenarios that produce the issue are added to
https://github.com/darbaoui/TestLaravelAuthentication/blob/main/tests/Feature/AuthenticationTest.php

**Comment by cosmastech** [comment]
I'm not _entirely sure_ this is a bug... it's just a consequence of how test cases simulate the application life-cycle. This particular issue may a problem if you're using a long-running process like Octane, but it looks like that's [designed to flush authentication state when a request has been handled](https://github.com/laravel/octane/blob/2.x/src/Listeners/FlushAuthenticationState.php).

The way guards are designed, the user is resolved from the token and then cached as property in the auth Guard. [On subsequent requests, it just pulls the cached user from the guard](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Auth/RequestGuard.php#L50-L55).

It's worth noting calling `TestCase@getJson()` inside of tests is not the exactly same as if you were to write a bash script that used curl to hit the endpoint twice. In a web request, the application cold starts, and once the response is sent back, execution stops (so there's no shared state). Calling `getJson()` doesn't make an HTTP request, it leverages the framework to find the matching controller and execute **as if** there were an HTTP request. However, the application state remains in tact. This means the `RequestGuard::$user` is still cached.

The tests classes simulate booting up and tearing down the application, but it's at the start/end of a test case, not for `getJson()` call. If they did, test suite time would be unbearably long. 😆 


If you want make the test more realistic, after you make the first API request, add this line:
```diff
        $response1
             ->assertJson(
                 static fn (AssertableJson $json) => $json
                     ->where('email', static fn (string $email) => str($email)->is($email1))
                     ->etc()
             )
        ;

++      $this->app->make('auth')->guard()->forgetUser();
        $response2 = $this->withHeaders([
            'Authorization' => 'Bearer '.$token2
        ])->getJson('api/user');
```

the test should pass.

**Comment by crynobone** [comment]
Thanks @cosmastech

**Comment by darbaoui** [comment]
@cosmastech, thanks for your response, but in the real case, using Postman, I can re-use the token even after revoking it, and I can still get the user data instead of receiving a 401. I think the **requestGuard** should have a clear and clean way to log out the user, similar to how **sessionGuard** does, or the documentation should include an additional step after revoking the token, such as adding
```diff
public function logout(Request $request)
{
   $request->user()->currentAccessToken()->delete();
++ $this->app->make('auth')->guard()->forgetUser();
}

```

**Comment by cosmastech** [comment]
@darbaoui I just made three requests:

```shell
➜  TestLaravelAuthentication git:(main) ✗ curl -H "Accept: application/json" "http://127.0.0.1:8000/api/user" -H "Authorization: Bearer 3|vK6I7xGvlolPuSE1e6qJhs6L0Ek8ke0uMRSVl6oV94efd5c9" | jq
{
  "id": 1,
  "name": "Horacio Tillman",
  "email": "mosinski@example.org",
  "email_verified_at": "2024-12-08T13:13:52.000000Z",
  "created_at": "2024-12-08T13:13:52.000000Z",
  "updated_at": "2024-12-08T13:13:52.000000Z"
}

➜  TestLaravelAuthentication git:(main) ✗ curl -H "Accept: application/json" "http://127.0.0.1:8000/api/logout" -H "Authorization: Bearer 3|vK6I7xGvlolPuSE1e6qJhs6L0Ek8ke0uMRSVl6oV94efd5c9" | jq
[]

➜  TestLaravelAuthentication git:(main) ✗ curl -H "Accept: application/json" "http://127.0.0.1:8000/api/user" -H "Authorization: Bearer 3|vK6I7xGvlolPuSE1e6qJhs6L0Ek8ke0uMRSVl6oV94efd5c9" | jq
{
  "message": "Unauthenticated."
}

```

Is this not what you're seeing? Or are you trying to perform additional user actions after destroying the token in the logout route?

Maybe it would make sense to add a method to HasApiTokens that destroys the token, sets $accessToken to null, and removes the user from the session? You wouldn't necessarily need to add this to the library, as you can just write your own HasApiTokens trait and give it an additional method.
